In [11]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier

In [205]:
train_file_path = 'Train_Dataset.csv'
test_file_path = 'Test_Dataset.csv'

train_data = pd.read_csv(train_file_path)
test_data = pd.read_csv(test_file_path)

In [206]:
train_data.dropna(subset=['EmployeeID'], thresh=1,inplace=True)

In [207]:
def Encode(df):
    le = LabelEncoder()
    for col in df.select_dtypes(include=['object']):
        df[col] = le.fit_transform(df[col].astype(str))
    return df

In [208]:
def Fillnas(df):
    df.fillna(df.median(numeric_only=True), inplace=True)
    return df

In [209]:
#train_data['MaritalStatus'] = train_data['MaritalStatus'].apply(lambda x: x if  x != 'M' else 'Married')
def conv_gender(df):
    df['MaritalStatus'] = df['MaritalStatus'].apply(lambda x: x if  x != 'M' else 'Married')
    return df

In [210]:
def drop_col(df):
    df.drop('SalaryHikelastYear',axis=1,inplace=True)
    #df.drop('ESOPs',axis=1,inplace=True)
    return df

In [211]:
def run_pipeline(df):
#    pipeline = df.pipe(conv_gender).pipe(Fillnas).pipe(Encode).pipe(drop_col)
    pipeline = df.pipe(Fillnas).pipe(Encode).pipe(drop_col)
    pipeline

In [212]:
run_pipeline(train_data)

In [213]:
#train_data.fillna(train_data.median(numeric_only=True), inplace=True)

In [214]:
train_data.describe(percentiles=[.01,.25,.5,.75,0.9,.95,.99]).T

,count,mean,std,min,1%,25%,50%,75%,90%,95%,99%,max
EmployeeID,5180.0,5.112590e+06,1495.481528,5110001.0,5110052.79,5111295.75,5112590.5,5113885.25,5114662.1,5114921.05,5115128.21,5115180.0
Attrition,5180.0,2.789575e-01,0.448530,0.0,0.00,0.00,0.0,1.00,1.0,1.00,1.00,1.0
Age,5180.0,3.704093e+01,8.965977,18.0,20.00,31.00,36.0,42.00,50.0,54.00,59.00,61.0
TravelProfile,5180.0,1.107915e+00,0.535057,0.0,0.00,1.00,1.0,1.00,2.0,2.00,2.00,2.0
Department,5180.0,7.382239e-01,0.980110,0.0,0.00,0.00,0.0,2.00,2.0,2.00,3.00,3.0
HomeToWork,5180.0,1.100367e+01,8.257384,1.0,1.00,5.00,9.0,15.00,25.0,28.00,31.00,121.0
EducationField,5180.0,2.762741e+00,2.180032,0.0,0.00,0.00,3.0,5.00,5.0,5.00,5.00,5.0
Gender,5180.0,1.479537e+00,0.733818,0.0,0.00,1.00,2.0,2.00,2.0,2.00,2.00,3.0
HourlnWeek,5180.0,5.803629e+01,12.633586,10.0,31.00,50.00,59.0,67.00,75.0,79.00,82.00,99.0
Involvement,5180.0,3.226641e+00,0.872431,1.0,1.00,3.00,3.0,4.00,4.0,5.00,5.00,5.0
WorkLifeBalance,5180.0,3.012741e+00,1.410602,1.0,1.00,2.00,3.0,4.00,5.0,5.00,5.00,5.0
Designation,5180.0,1.728764e+00,0.982558,0.0,0.00,1.00,2.0,2.00,3.0,4.00,4.00,5.0
JobSatisfaction,5180.0,3.144402e+00,1.342776,1.0,1.00,2.00,3.0,4.00,5.0,5.00,5.00,5.0
NumCompaniesWorked,5180.0,3.157336e+00,2.606036,0.0,0.00,1.00,2.0,5.00,7.0,9.00,10.00,21.0
OverTime,5180.0,3.135135e-01,0.463966,0.0,0.00,0.00,0.0,1.00,1.0,1.00,1.00,1.0
WorkExperience,5180.0,1.108764e+01,7.666366,0.0,1.00,6.00,9.0,15.00,22.0,27.00,35.00,41.0
LastPromotion,5180.0,2.531853e+00,3.217535,0.0,0.00,1.00,1.0,3.00,7.0,10.00,15.00,16.0
CurrentProfile,5180.0,4.302124e+00,3.522750,0.0,0.00,2.00,3.0,7.00,9.0,11.00,14.00,18.0
MaritalStatus,5180.0,1.801158e+00,1.112445,0.0,0.00,1.00,2.0,3.00,3.0,3.00,3.00,3.0
MonthlyIncome,5180.0,2.166479e+04,4731.987445,1000.0,16420.00,18377.00,20160.0,23346.00,28744.0,33041.25,35208.30,95000.0

In [1]:
pd.DataFrame([train_data['TravelProfile'].value_counts(),
train_data['Department'].value_counts(),
train_data['EducationField'].value_counts(),
train_data['Gender'].value_counts(),
train_data['Designation'].value_counts(),
train_data['MaritalStatus'].value_counts()])

NameError: name 'pd' is not defined

In [217]:
train_data.shape

(5180, 20)

In [218]:
train_data.describe(percentiles=[.25,.5,.75,.8,.9,.95,.99]).T

,count,mean,std,min,25%,50%,75%,80%,90%,95%,99%,max
EmployeeID,5180.0,5.112590e+06,1495.481528,5110001.0,5111295.75,5112590.5,5113885.25,5114144.2,5114662.1,5114921.05,5115128.21,5115180.0
Attrition,5180.0,2.789575e-01,0.448530,0.0,0.00,0.0,1.00,1.0,1.0,1.00,1.00,1.0
Age,5180.0,3.704093e+01,8.965977,18.0,31.00,36.0,42.00,45.0,50.0,54.00,59.00,61.0
TravelProfile,5180.0,1.107915e+00,0.535057,0.0,1.00,1.0,1.00,2.0,2.0,2.00,2.00,2.0
Department,5180.0,7.382239e-01,0.980110,0.0,0.00,0.0,2.00,2.0,2.0,2.00,3.00,3.0
HomeToWork,5180.0,1.100367e+01,8.257384,1.0,5.00,9.0,15.00,18.0,25.0,28.00,31.00,121.0
EducationField,5180.0,2.762741e+00,2.180032,0.0,0.00,3.0,5.00,5.0,5.0,5.00,5.00,5.0
Gender,5180.0,1.479537e+00,0.733818,0.0,1.00,2.0,2.00,2.0,2.0,2.00,2.00,3.0
HourlnWeek,5180.0,5.803629e+01,12.633586,10.0,50.00,59.0,67.00,69.0,75.0,79.00,82.00,99.0
Involvement,5180.0,3.226641e+00,0.872431,1.0,3.00,3.0,4.00,4.0,4.0,5.00,5.00,5.0
WorkLifeBalance,5180.0,3.012741e+00,1.410602,1.0,2.00,3.0,4.00,4.0,5.0,5.00,5.00,5.0
Designation,5180.0,1.728764e+00,0.982558,0.0,1.00,2.0,2.00,2.0,3.0,4.00,4.00,5.0
JobSatisfaction,5180.0,3.144402e+00,1.342776,1.0,2.00,3.0,4.00,5.0,5.0,5.00,5.00,5.0
NumCompaniesWorked,5180.0,3.157336e+00,2.606036,0.0,1.00,2.0,5.00,5.0,7.0,9.00,10.00,21.0
OverTime,5180.0,3.135135e-01,0.463966,0.0,0.00,0.0,1.00,1.0,1.0,1.00,1.00,1.0
WorkExperience,5180.0,1.108764e+01,7.666366,0.0,6.00,9.0,15.00,17.0,22.0,27.00,35.00,41.0
LastPromotion,5180.0,2.531853e+00,3.217535,0.0,1.00,1.0,3.00,4.0,7.0,10.00,15.00,16.0
CurrentProfile,5180.0,4.302124e+00,3.522750,0.0,2.00,3.0,7.00,8.0,9.0,11.00,14.00,18.0
MaritalStatus,5180.0,1.801158e+00,1.112445,0.0,1.00,2.0,3.00,3.0,3.0,3.00,3.00,3.0
MonthlyIncome,5180.0,2.166479e+04,4731.987445,1000.0,18377.00,20160.0,23346.00,24823.2,28744.0,33041.25,35208.30,95000.0

In [219]:
train_data.skew()

EmployeeID            0.000000
Attrition             0.986012
Age                   0.462018
TravelProfile         0.091400
Department            0.695080
HomeToWork            1.333220
EducationField       -0.209343
Gender               -0.891258
HourlnWeek           -0.234548
Involvement          -0.518513
WorkLifeBalance      -0.020089
Designation           0.620840
JobSatisfaction      -0.145593
NumCompaniesWorked    1.126677
OverTime              0.804191
WorkExperience        1.194552
LastPromotion         1.995481
CurrentProfile        0.883728
MaritalStatus        -0.457692
MonthlyIncome         2.025872
dtype: float64

In [220]:
# It is reducing the accuracy. So we will not do this
train_data.drop(train_data[train_data['MonthlyIncome']==95000].index[0], axis=0, inplace=True)

In [221]:
train_data.skew()

EmployeeID           -0.000342
Attrition             0.985713
Age                   0.461909
TravelProfile         0.091277
Department            0.694773
HomeToWork            1.332925
EducationField       -0.209001
Gender               -0.891607
HourlnWeek           -0.234796
Involvement          -0.518202
WorkLifeBalance      -0.020435
Designation           0.620528
JobSatisfaction      -0.145368
NumCompaniesWorked    1.127330
OverTime              0.804855
WorkExperience        1.194262
LastPromotion         1.995285
CurrentProfile        0.883669
MaritalStatus        -0.458114
MonthlyIncome         1.412435
dtype: float64

In [222]:
train_data.describe(percentiles=[.25,.5,.75,.8,.9,.95,.99]).T

,count,mean,std,min,25%,50%,75%,80%,90%,95%,99%,max
EmployeeID,5179.0,5.112591e+06,1495.553164,5110001.0,5111295.5,5112591.0,5113885.5,5114144.4,5114662.2,5114921.1,5115128.22,5115180.0
Attrition,5179.0,2.790114e-01,0.448556,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.00,1.0
Age,5179.0,3.704113e+01,8.966831,18.0,31.0,36.0,42.0,45.0,50.0,54.0,59.00,61.0
TravelProfile,5179.0,1.107936e+00,0.535107,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.00,2.0
Department,5179.0,7.383665e-01,0.980151,0.0,0.0,0.0,2.0,2.0,2.0,2.0,3.00,3.0
HomeToWork,5179.0,1.100463e+01,8.257888,1.0,5.0,9.0,15.0,18.0,25.0,28.0,31.00,121.0
EducationField,5179.0,2.762309e+00,2.180021,0.0,0.0,3.0,5.0,5.0,5.0,5.0,5.00,5.0
Gender,5179.0,1.479629e+00,0.733858,0.0,1.0,2.0,2.0,2.0,2.0,2.0,2.00,3.0
HourlnWeek,5179.0,5.803746e+01,12.634527,10.0,50.0,59.0,67.0,69.0,75.0,79.0,82.00,99.0
Involvement,5179.0,3.226492e+00,0.872449,1.0,3.0,3.0,4.0,4.0,4.0,5.0,5.00,5.0
WorkLifeBalance,5179.0,3.012937e+00,1.410668,1.0,2.0,3.0,4.0,4.0,5.0,5.0,5.00,5.0
Designation,5179.0,1.728905e+00,0.982601,0.0,1.0,2.0,2.0,2.0,3.0,4.0,4.00,5.0
JobSatisfaction,5179.0,3.144043e+00,1.342658,1.0,2.0,3.0,4.0,5.0,5.0,5.0,5.00,5.0
NumCompaniesWorked,5179.0,3.156208e+00,2.605022,0.0,1.0,2.0,5.0,5.0,7.0,9.0,10.00,21.0
OverTime,5179.0,3.133810e-01,0.463913,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.00,1.0
WorkExperience,5179.0,1.108863e+01,7.666780,0.0,6.0,9.0,15.0,17.0,22.0,27.0,35.00,41.0
LastPromotion,5179.0,2.532342e+00,3.217653,0.0,1.0,1.0,3.0,4.0,7.0,10.0,15.00,16.0
CurrentProfile,5179.0,4.302954e+00,3.522582,0.0,2.0,3.0,7.0,8.0,9.0,11.0,14.00,18.0
MaritalStatus,5179.0,1.801506e+00,1.112271,0.0,1.0,2.0,3.0,3.0,3.0,3.0,3.00,3.0
MonthlyIncome,5179.0,2.165063e+04,4621.384395,1000.0,18377.0,20160.0,23341.0,24805.0,28742.4,33041.0,35198.10,35999.0

In [224]:
#train_data.loc(train_data['MonthlyIncome']==95000)
#train_data[train_data['MonthlyIncome']==95000].index[0]

In [225]:
train_data.corr()

,EmployeeID,Attrition,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,WorkLifeBalance,Designation,JobSatisfaction,NumCompaniesWorked,OverTime,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
EmployeeID,1.000000,-0.023154,0.021753,-0.000489,-0.011154,-0.017486,0.020413,-0.017553,0.010942,0.002442,-0.003540,-0.004421,-0.004392,-0.000644,-0.008948,0.025721,0.003855,0.012133,-0.016198,0.021305
Attrition,-0.023154,1.000000,-0.180511,0.142441,0.128292,0.086199,-0.017881,0.090313,0.021089,0.144455,0.013523,-0.091695,0.126939,0.050125,0.281360,-0.218176,-0.038568,-0.199198,0.121478,-0.203398
Age,0.021753,-0.180511,1.000000,-0.013201,-0.078716,0.014014,0.010330,-0.130312,-0.009205,-0.023137,-0.012043,0.182799,-0.016373,0.300622,0.007486,0.660839,0.239809,0.219159,-0.054155,0.490262
TravelProfile,-0.000489,0.142441,-0.013201,1.000000,-0.013899,-0.017901,0.034744,-0.030547,-0.013567,-0.008525,-0.022318,-0.018901,-0.027289,-0.027892,0.047316,-0.004592,0.013844,0.000476,0.025296,-0.025983
Department,-0.011154,0.128292,-0.078716,-0.013899,1.000000,-0.002618,0.064165,-0.021507,-0.018406,0.043112,-0.008586,0.067911,-0.009219,-0.050854,0.005790,-0.079513,-0.011799,-0.042427,0.071575,0.005633
HomeToWork,-0.017486,0.086199,0.014014,-0.017901,-0.002618,1.000000,-0.012608,-0.020954,0.055784,-0.003041,0.019823,0.002202,0.010095,-0.010475,0.048369,0.013199,0.015396,0.015886,0.005924,0.002467
EducationField,0.020413,-0.017881,0.010330,0.034744,0.064165,-0.012608,1.000000,-0.012865,0.028026,0.003738,0.024173,-0.012957,-0.034685,-0.024917,0.023444,-0.015251,-0.012353,0.005632,-0.001063,0.003153
Gender,-0.017553,0.090313,-0.130312,-0.030547,-0.021507,-0.020954,-0.012865,1.000000,0.008081,0.007358,0.023107,-0.122288,-0.018974,-0.045967,0.000319,-0.213645,-0.111995,-0.137652,-0.032873,-0.242836
HourlnWeek,0.010942,0.021089,-0.009205,-0.013567,-0.018406,0.055784,0.028026,0.008081,1.000000,-0.016135,0.009042,-0.008360,0.049717,0.012326,0.042742,-0.021040,-0.030314,-0.000155,-0.049879,-0.021821
Involvement,0.002442,0.144455,-0.023137,-0.008525,0.043112,-0.003041,0.003738,0.007358,-0.016135,1.000000,0.001542,0.041675,-0.022416,0.007203,0.017848,-0.005167,0.013523,-0.047153,0.041163,0.007129
WorkLifeBalance,-0.003540,0.013523,-0.012043,-0.022318,-0.008586,0.019823,0.024173,0.023107,0.009042,0.001542,1.000000,-0.021712,0.012373,-0.006068,0.017412,-0.020391,-0.012325,-0.000439,-0.030488,-0.001924
Designation,-0.004421,-0.091695,0.182799,-0.018901,0.067911,0.002202,-0.012957,-0.122288,-0.008360,0.041675,-0.021712,1.000000,-0.016653,0.066569,-0.022036,0.269188,0.139600,0.234361,0.032923,0.400447
JobSatisfaction,-0.004392,0.126939,-0.016373,-0.027289,-0.009219,0.010095,-0.034685,-0.018974,0.049717,-0.022416,0.012373,-0.016653,1.000000,0.051928,-0.025047,-0.003079,0.013137,0.008044,-0.031932,-0.014578
NumCompaniesWorked,-0.000644,0.050125,0.300622,-0.027892,-0.050854,-0.010475,-0.024917,-0.045967,0.012326,0.007203,-0.006068,0.066569,0.051928,1.000000,-0.007755,0.236901,0.012449,-0.064907,0.014702,0.157570
OverTime,-0.008948,0.281360,0.007486,0.047316,0.005790,0.048369,0.023444,0.000319,0.042742,0.017848,0.017412,-0.022036,-0.025047,-0.007755,1.000000,-0.031648,-0.031567,-0.055390,-0.005930,-0.021005
WorkExperience,0.025721,-0.218176,0.660839,-0.004592,-0.079513,0.013199,-0.015251,-0.213645,-0.021040,-0.005167,-0.020391,0.269188,-0.003079,0.236901,-0.031648,1.000000,0.427394,0.479886,-0.008717,0.767606
LastPromotion,0.003855,-0.038568,0.239809,0.013844,-0.011799,0.015396,-0.012353,-0.111995,-0.030314,0.013523,-0.012325,0.139600,0.013137,0.012449,-0.031567,0.427394,1.000000,0.517156,-0.008189,0.370046
CurrentProfile,0.012133,-0.199198,0.219159,0.000476,-0.042427,0.015886,0.005632,-0.137652,-0.000155,-0.047153,-0.000439,0.234361,0.008044,-0.064907,-0.055390,0.479886,0.517156,1.000000,0.006380,0.395205
MaritalStatus,-0.016198,0.121478,-0.054155,0.025296,0.071575,0.005924,-0.001063,-0.032873,-0.049879,0.041163,-0.030488,0.032923,-0.031932,0.014702,-0.005930,-0.008717,-0.008189,0.006380,1.000000,0.027227
MonthlyIncome,0.021305,-0.203398,0.490262,-0.025983,0.005633,0.002467,0.003153,-0.242836,-0.021821,0.007129,-0.001924,0.400447,-0.014578,0.157570,-0.021005,0.767606,0.370046,0.395205,0.027227,1.000000

In [226]:
train_data[train_data['MonthlyIncome']>36000].count()

EmployeeID            0
Attrition             0
Age                   0
TravelProfile         0
Department            0
HomeToWork            0
EducationField        0
Gender                0
HourlnWeek            0
Involvement           0
WorkLifeBalance       0
Designation           0
JobSatisfaction       0
NumCompaniesWorked    0
OverTime              0
WorkExperience        0
LastPromotion         0
CurrentProfile        0
MaritalStatus         0
MonthlyIncome         0
dtype: int64

In [227]:
train_data[train_data['NumCompaniesWorked']>19].count()

EmployeeID            1
Attrition             1
Age                   1
TravelProfile         1
Department            1
HomeToWork            1
EducationField        1
Gender                1
HourlnWeek            1
Involvement           1
WorkLifeBalance       1
Designation           1
JobSatisfaction       1
NumCompaniesWorked    1
OverTime              1
WorkExperience        1
LastPromotion         1
CurrentProfile        1
MaritalStatus         1
MonthlyIncome         1
dtype: int64

In [228]:
train_data.skew()

EmployeeID           -0.000342
Attrition             0.985713
Age                   0.461909
TravelProfile         0.091277
Department            0.694773
HomeToWork            1.332925
EducationField       -0.209001
Gender               -0.891607
HourlnWeek           -0.234796
Involvement          -0.518202
WorkLifeBalance      -0.020435
Designation           0.620528
JobSatisfaction      -0.145368
NumCompaniesWorked    1.127330
OverTime              0.804855
WorkExperience        1.194262
LastPromotion         1.995285
CurrentProfile        0.883669
MaritalStatus        -0.458114
MonthlyIncome         1.412435
dtype: float64

In [229]:
scale = StandardScaler()

In [230]:
train_data.corr()

,EmployeeID,Attrition,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,WorkLifeBalance,Designation,JobSatisfaction,NumCompaniesWorked,OverTime,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
EmployeeID,1.000000,-0.023154,0.021753,-0.000489,-0.011154,-0.017486,0.020413,-0.017553,0.010942,0.002442,-0.003540,-0.004421,-0.004392,-0.000644,-0.008948,0.025721,0.003855,0.012133,-0.016198,0.021305
Attrition,-0.023154,1.000000,-0.180511,0.142441,0.128292,0.086199,-0.017881,0.090313,0.021089,0.144455,0.013523,-0.091695,0.126939,0.050125,0.281360,-0.218176,-0.038568,-0.199198,0.121478,-0.203398
Age,0.021753,-0.180511,1.000000,-0.013201,-0.078716,0.014014,0.010330,-0.130312,-0.009205,-0.023137,-0.012043,0.182799,-0.016373,0.300622,0.007486,0.660839,0.239809,0.219159,-0.054155,0.490262
TravelProfile,-0.000489,0.142441,-0.013201,1.000000,-0.013899,-0.017901,0.034744,-0.030547,-0.013567,-0.008525,-0.022318,-0.018901,-0.027289,-0.027892,0.047316,-0.004592,0.013844,0.000476,0.025296,-0.025983
Department,-0.011154,0.128292,-0.078716,-0.013899,1.000000,-0.002618,0.064165,-0.021507,-0.018406,0.043112,-0.008586,0.067911,-0.009219,-0.050854,0.005790,-0.079513,-0.011799,-0.042427,0.071575,0.005633
HomeToWork,-0.017486,0.086199,0.014014,-0.017901,-0.002618,1.000000,-0.012608,-0.020954,0.055784,-0.003041,0.019823,0.002202,0.010095,-0.010475,0.048369,0.013199,0.015396,0.015886,0.005924,0.002467
EducationField,0.020413,-0.017881,0.010330,0.034744,0.064165,-0.012608,1.000000,-0.012865,0.028026,0.003738,0.024173,-0.012957,-0.034685,-0.024917,0.023444,-0.015251,-0.012353,0.005632,-0.001063,0.003153
Gender,-0.017553,0.090313,-0.130312,-0.030547,-0.021507,-0.020954,-0.012865,1.000000,0.008081,0.007358,0.023107,-0.122288,-0.018974,-0.045967,0.000319,-0.213645,-0.111995,-0.137652,-0.032873,-0.242836
HourlnWeek,0.010942,0.021089,-0.009205,-0.013567,-0.018406,0.055784,0.028026,0.008081,1.000000,-0.016135,0.009042,-0.008360,0.049717,0.012326,0.042742,-0.021040,-0.030314,-0.000155,-0.049879,-0.021821
Involvement,0.002442,0.144455,-0.023137,-0.008525,0.043112,-0.003041,0.003738,0.007358,-0.016135,1.000000,0.001542,0.041675,-0.022416,0.007203,0.017848,-0.005167,0.013523,-0.047153,0.041163,0.007129
WorkLifeBalance,-0.003540,0.013523,-0.012043,-0.022318,-0.008586,0.019823,0.024173,0.023107,0.009042,0.001542,1.000000,-0.021712,0.012373,-0.006068,0.017412,-0.020391,-0.012325,-0.000439,-0.030488,-0.001924
Designation,-0.004421,-0.091695,0.182799,-0.018901,0.067911,0.002202,-0.012957,-0.122288,-0.008360,0.041675,-0.021712,1.000000,-0.016653,0.066569,-0.022036,0.269188,0.139600,0.234361,0.032923,0.400447
JobSatisfaction,-0.004392,0.126939,-0.016373,-0.027289,-0.009219,0.010095,-0.034685,-0.018974,0.049717,-0.022416,0.012373,-0.016653,1.000000,0.051928,-0.025047,-0.003079,0.013137,0.008044,-0.031932,-0.014578
NumCompaniesWorked,-0.000644,0.050125,0.300622,-0.027892,-0.050854,-0.010475,-0.024917,-0.045967,0.012326,0.007203,-0.006068,0.066569,0.051928,1.000000,-0.007755,0.236901,0.012449,-0.064907,0.014702,0.157570
OverTime,-0.008948,0.281360,0.007486,0.047316,0.005790,0.048369,0.023444,0.000319,0.042742,0.017848,0.017412,-0.022036,-0.025047,-0.007755,1.000000,-0.031648,-0.031567,-0.055390,-0.005930,-0.021005
WorkExperience,0.025721,-0.218176,0.660839,-0.004592,-0.079513,0.013199,-0.015251,-0.213645,-0.021040,-0.005167,-0.020391,0.269188,-0.003079,0.236901,-0.031648,1.000000,0.427394,0.479886,-0.008717,0.767606
LastPromotion,0.003855,-0.038568,0.239809,0.013844,-0.011799,0.015396,-0.012353,-0.111995,-0.030314,0.013523,-0.012325,0.139600,0.013137,0.012449,-0.031567,0.427394,1.000000,0.517156,-0.008189,0.370046
CurrentProfile,0.012133,-0.199198,0.219159,0.000476,-0.042427,0.015886,0.005632,-0.137652,-0.000155,-0.047153,-0.000439,0.234361,0.008044,-0.064907,-0.055390,0.479886,0.517156,1.000000,0.006380,0.395205
MaritalStatus,-0.016198,0.121478,-0.054155,0.025296,0.071575,0.005924,-0.001063,-0.032873,-0.049879,0.041163,-0.030488,0.032923,-0.031932,0.014702,-0.005930,-0.008717,-0.008189,0.006380,1.000000,0.027227
MonthlyIncome,0.021305,-0.203398,0.490262,-0.025983,0.005633,0.002467,0.003153,-0.242836,-0.021821,0.007129,-0.001924,0.400447,-0.014578,0.157570,-0.021005,0.767606,0.370046,0.395205,0.027227,1.000000

In [231]:
train_data.head()

,EmployeeID,Attrition,Age,TravelProfile,Department,HomeToWork,EducationField,Gender,HourlnWeek,Involvement,WorkLifeBalance,Designation,JobSatisfaction,NumCompaniesWorked,OverTime,WorkExperience,LastPromotion,CurrentProfile,MaritalStatus,MonthlyIncome
0,5110001.0,0.0,35.0,1,0,5.0,0,2,69.0,1.0,1.0,1,1.0,1.0,1.0,7.0,2.0,3.0,1,18932.0
1,5110002.0,1.0,32.0,2,2,5.0,5,1,62.0,4.0,3.0,1,2.0,8.0,0.0,4.0,1.0,3.0,3,18785.0
2,5110003.0,0.0,31.0,1,0,5.0,5,0,45.0,5.0,3.0,2,2.0,3.0,0.0,12.0,1.0,3.0,3,22091.0
3,5110004.0,0.0,34.0,2,2,10.0,5,1,32.0,3.0,2.0,2,4.0,1.0,0.0,5.0,1.0,3.0,0,20302.0
4,5110005.0,0.0,37.0,0,0,27.0,5,1,49.0,3.0,4.0,2,4.0,8.0,0.0,12.0,1.0,9.0,0,21674.0

In [234]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5179 entries, 0 to 5179
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EmployeeID          5179 non-null   float64
 1   Attrition           5179 non-null   float64
 2   Age                 5179 non-null   float64
 3   TravelProfile       5179 non-null   int32
 4   Department          5179 non-null   int32
 5   HomeToWork          5179 non-null   float64
 6   EducationField      5179 non-null   int32
 7   Gender              5179 non-null   int32
 8   HourlnWeek          5179 non-null   float64
 9   Involvement         5179 non-null   float64
 10  WorkLifeBalance     5179 non-null   float64
 11  Designation         5179 non-null   int32
 12  JobSatisfaction     5179 non-null   float64
 13  NumCompaniesWorked  5179 non-null   float64
 14  OverTime            5179 non-null   float64
 15  WorkExperience      5179 non-null   float64
 16  LastPromotion       5179 non-null   float64
 17  CurrentProfile      5179 non-null   float64
 18  MaritalStatus       5179 non-null   int32
 19  MonthlyIncome       5179 non-null   float64
dtypes: float64(14), int32(6)
memory usage: 728.3 KB

In [235]:
# split features and target from train data
X = train_data.drop(columns=['EmployeeID', 'Attrition'])
y = train_data['Attrition']

from scipy.stats import boxcox
#X['MonthlyIncome'], lam = boxcox(X['MonthlyIncome'])
#X['HomeToWork'], lam = boxcox(X['HomeToWork'])
#X['NumCompaniesWorked'] = X['NumCompaniesWorked']**(1/2)
#X['WorkExperience'] = X['WorkExperience']**(1/2)
#X['LastPromotion'] = X['LastPromotion']**(1/2)

X = scale.fit_transform(X)

In [236]:
pd.DataFrame(X).skew()

0     0.461909
1     0.091277
2     0.694773
3     1.332925
4    -0.209001
5    -0.891607
6    -0.234796
7    -0.518202
8    -0.020435
9     0.620528
10   -0.145368
11    1.127330
12    0.804855
13    1.194262
14    1.995285
15    0.883669
16   -0.458114
17    1.412435
dtype: float64

In [237]:
# split train data into train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# build the gradient boosting vlassifier
gb_model = GradientBoostingClassifier(n_estimators=200, learning_rate=0.122, max_depth=9, random_state=42)
gb_model.fit(X_train, y_train)

# predictions on the validation set
y_val_pred_gb = gb_model.predict(X_val)

# accuracy for GBC
val_accuracy_gb = accuracy_score(y_val, y_val_pred_gb)

val_accuracy_gb

0.9932432432432432

In [238]:
val_accuracy_gb

0.9932432432432432

In [239]:
val_accuracy_gb        # (n_estimators=250, learning_rate=0.12, max_depth=9, random_state=42)

0.9932432432432432

In [240]:
val_accuracy_gb

0.9932432432432432

In [241]:
val_accuracy_gb

0.9932432432432432

In [242]:
val_accuracy_gb

0.9932432432432432

In [243]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,-0.227653,-0.201729,-0.753392,-0.727209,-1.267224,0.709157,0.867749,-2.552248,-1.427077,-0.741884,-1.597019,-0.827792,1.480204,-0.533343,-0.165460,-0.369922,-0.720673,-0.588328
1,-0.562252,1.667238,1.287307,-0.727209,1.026553,-0.653635,0.313658,0.886680,-0.009172,-0.741884,-0.852156,1.859585,-0.675582,-0.924679,-0.476276,-0.369922,1.077624,-0.620139
2,-0.673784,-0.201729,-0.753392,-0.727209,1.026553,-2.016428,-1.031991,2.032989,-0.009172,0.275922,-0.852156,-0.059970,-0.675582,0.118884,-0.476276,-0.369922,1.077624,0.095300
3,-0.339186,1.667238,1.287307,-0.121669,1.026553,-0.653635,-2.061017,-0.259629,-0.718124,0.275922,0.637571,-0.827792,-0.675582,-0.794234,-0.476276,-0.369922,-1.619821,-0.291851
4,-0.004587,-2.070696,-0.753392,1.937167,1.026553,-0.653635,-0.715368,-0.259629,0.699781,0.275922,0.637571,1.859585,-0.675582,0.118884,-0.476276,1.333538,-1.619821,0.005058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5174,-0.116120,-0.201729,-0.753392,0.241655,-1.267224,-2.016428,-0.398744,-0.259629,-0.009172,0.275922,-0.107292,0.323941,1.480204,-0.011561,-0.476276,0.197898,1.077624,0.106336
5175,-0.116120,-0.201729,0.266958,-0.242777,-1.267224,-0.653635,0.630282,-2.552248,0.699781,-0.741884,0.637571,2.243496,-0.675582,-0.402897,-0.787091,-0.653832,1.077624,-0.982836
5176,-0.896850,-0.201729,-0.753392,-0.242777,-1.267224,-0.653635,0.313658,0.886680,-0.718124,-0.741884,-1.597019,1.091763,-0.675582,-0.402897,-0.787091,-0.369922,-0.720673,-0.891296
5177,-1.231449,-0.201729,0.266958,1.816059,1.026553,-0.653635,0.234502,-0.259629,0.699781,-0.741884,-0.107292,-0.827792,-0.675582,-0.402897,0.766986,0.765718,-1.619821,-0.802570
5178,-0.116120,1.667238,1.287307,0.241655,1.026553,0.709157,1.263528,0.886680,-0.009172,-0.741884,1.382434,-0.827792,-0.675582,-1.316016,-0.787091,-1.221652,-1.619821,-0.999283

In [244]:
a = pd.DataFrame(X)
a.skew()

0     0.461909
1     0.091277
2     0.694773
3     1.332925
4    -0.209001
5    -0.891607
6    -0.234796
7    -0.518202
8    -0.020435
9     0.620528
10   -0.145368
11    1.127330
12    0.804855
13    1.194262
14    1.995285
15    0.883669
16   -0.458114
17    1.412435
dtype: float64

In [245]:
X.skew()

AttributeError: 'numpy.ndarray' object has no attribute 'skew'

In [246]:
# predictions on the test set using GBC
run_pipeline(test_data)
test_features = test_data.drop(columns=['EmployeeID'])
test_predictions_gb = gb_model.predict(test_features)

# submission dataframe for GBC
submission_df_gb = pd.DataFrame({
    'EmployeeID': test_data['EmployeeID'],
    'Attrition': test_predictions_gb
})

# Save the file for GBC
submission_file_path_gb = 'submission_attrition_model - '+str(val_accuracy_gb)[2:6]+'.csv'
submission_df_gb.to_csv(submission_file_path_gb, index=False)

val_accuracy_gb, submission_file_path_gb

C:\Python\Anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but GradientBoostingClassifier was fitted without feature names
  warnings.warn(

(0.9932432432432432, 'submission_attrition_model - 9932.csv')